# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d4383b17ae5659fe88e7e6922966e0be06750ba2dbb59dd774fca05c397734ef1263101f08a54adf2d125464177b4faaaa28b469a4c4cb16b64ef9f5862028

test:
  secret_key_base: fea3b52819cc7a9790e9ea4c5cbe559736dd37161cf730f2509e7a480cea98aa542d972b6b2c8c410a0e2d0244ba6c71ffb06900081448e0dd5ccb9d4ea43b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
